clients:
  client:
    cache_max_age: 900
    templates:
      image_gallery_template:
        width: 100
        height: 100
        manipulation: "resize_and_pad" #for possible values see image_service.rb